import { masterPrism, type HolographicProfile } from '../HolographicProfile';

type ProfileChanges = Pick<HolographicProfile, 'id' | 'name' | 'description'> & {
  labOnly?: boolean;
  diffraction?: Partial<HolographicProfile['diffraction']>;
  structure?: Partial<HolographicProfile['structure']>;
  glints?: Partial<HolographicProfile['glints']>;
  surface?: Partial<HolographicProfile['surface']>;
};
function original(p: ProfileChanges): HolographicProfile {
  return { ...masterPrism, ...p, status: 'development',
    diffraction: { ...masterPrism.diffraction, ...p.diffraction },
    structure: { ...masterPrism.structure, ...p.structure },
    glints: { ...masterPrism.glints, ...p.glints },
    surface: { ...masterPrism.surface, ...p.surface },
  };
}

export const originalProfiles = [masterPrism,
  original({ id: 'cathedral-prism', name: 'Cathedral prism', description: 'Eight engraved radial sectors, fine laser-cut rays and raised arch tracery split light into sharply separated spectral fans.',
    diffraction: { period: 1.16, bandwidth: .024, strength: 1.65, crossWidth: .25, secondaryOrder: .1 },
    structure: { field: 'cathedral', scale: 280, engraving: .38, relief: .035, facetTilt: .28, patternRelief: .38, normalVariance: .3 },
    glints: { density: .04, scale: 470, strength: 7, sharpness: 430, spread: .22 },
    surface: { roughness: .23, metalness: .77, laminate: .4, laminateRoughness: .19, foilReflectance: .08 },
  }),
  original({ id: 'spectral-lattice', name: 'Spectral lattice', description: 'Two intersecting fine gratings with sparse embossed junctions and coherent spectral bands across a flat optical lattice.',
    diffraction: { period: 1.25, bandwidth: .027, strength: 1.3, crossWidth: .32, secondaryOrder: .12, crossing: .5 },
    structure: { field: 'lattice', scale: 210, engraving: .2, relief: .025, facetTilt: .2, patternRelief: .15, normalVariance: .3 },
    glints: { density: .04, scale: 450, strength: 4, sharpness: 340, spread: .18 },
    surface: { roughness: .28, metalness: .75, laminate: .34, laminateRoughness: .19, foilReflectance: .08 },
  }),
  original({ id: 'black-chrome-prism', name: 'Black chrome prism', description: 'Polished dark chrome with narrow engraved spectral lines and rare, sharp white microfacet flashes.',
    diffraction: { period: .88, bandwidth: .017, strength: 2.4, crossWidth: .17, secondaryOrder: .06 },
    structure: { field: 'chrome', scale: 140, engraving: .16, relief: .012, facetTilt: .2, normalVariance: .1 },
    glints: { density: .012, scale: 380, strength: 27, sharpness: 640, spread: .15 },
    surface: { roughness: .16, metalness: .95, laminate: .3, laminateRoughness: .11, foilReflectance: .035, substrateDarkening: .8 },
  }),
  original({ id: 'opal', name: 'Opal', description: 'Pearlescent nacre domains with variable film thickness, soft ceramic reflections and restrained microcrystalline sparkle.',
    diffraction: { strength: 0, secondaryOrder: 0 },
    structure: { field: 'opal', scale: 8, engraving: 0, relief: .02, facetTilt: .35, normalVariance: .25 },
    glints: { density: .018, scale: 510, strength: 2.5, sharpness: 160, spread: .22 },
    surface: { roughness: .34, metalness: .38, laminate: .58, laminateRoughness: .16, sheen: .72, iridescence: 1, filmIOR: 2.15, filmMin: 120, filmMax: 680, foilReflectance: .035, pearlBody: .12 },
  }),
  original({ id: 'solar-fresnel', name: 'Solar Fresnel', description: 'Fine elliptical optical grooves produce isolated spectral arcs and narrow silver ridges as the card crosses the light.',
    diffraction: { period: 1.28, bandwidth: .027, strength: 1.45, crossWidth: .21, secondaryOrder: .08 },
    structure: { field: 'fresnel', scale: 135, engraving: .15, relief: .04, facetTilt: .25, patternRelief: .18, normalVariance: .2 },
    glints: { density: .018, scale: 480, strength: 4, sharpness: 310 },
    surface: { roughness: .25, metalness: .76, laminateRoughness: .16, foilReflectance: .09 },
  }),
  original({ id: 'liquid-spectrum', name: 'Liquid spectrum', description: 'A stationary, fluid grating field produces changing pools of spectral reflection and narrow ribbons at flow convergences.',
    diffraction: { period: 1.3, bandwidth: .046, strength: .62, crossWidth: .31, secondaryOrder: .06 },
    structure: { field: 'liquid', scale: 16, engraving: .12, relief: .025, facetTilt: .5, normalVariance: .12 },
    glints: { density: .02, scale: 420, strength: 4.5, sharpness: 250, spread: .3 },
    surface: { roughness: .27, metalness: .72, laminateRoughness: .14, anisotropy: .25, foilReflectance: .06 },
  }),
  original({ id: 'aurora-silk', name: 'Aurora silk', description: 'Elongated satin interference with a curved local grating field and broad anisotropic silver reflection.',
    diffraction: { period: 1.15, bandwidth: .092, strength: .6, crossWidth: .48, secondaryOrder: .03 },
    structure: { field: 'silk', scale: 20, engraving: .18, relief: .045, facetTilt: .5 },
    glints: { density: .015, strength: 3, scale: 450 },
    surface: { roughness: .36, metalness: .66, laminateRoughness: .22, anisotropy: .68 },
  }),
  original({ id: 'crystal-shard', name: 'Crystal shard', description: 'Irregular elongated crystal facets with independently inclined optical normals, grating orientation and spacing.',
    diffraction: { period: 1.38, bandwidth: .035, strength: .9, crossWidth: .24, secondaryOrder: .14 },
    structure: { field: 'crystal', scale: 17, engraving: .12, relief: .035, facetTilt: .28 },
    glints: { density: .04, strength: 7 }, surface: { roughness: .23, metalness: .74 },
  }),
  original({ id: 'microdiamond', name: 'Microdiamond', description: 'Ordered pyramidal microprisms with four facet normals per cell and two crossing grating directions.',
    diffraction: { period: 1.1, bandwidth: .028, strength: .85, crossWidth: .24, secondaryOrder: .16, crossing: .5 },
    structure: { field: 'diamond', scale: 275, engraving: .15, relief: .025, facetTilt: .55, normalVariance: .6 },
    glints: { density: 1, scale: 275, sharpness: 370, strength: 13, spread: .14, ordered: true },
    surface: { roughness: .24, metalness: .72, laminateRoughness: .15 },
  }),
  original({ id: 'starfield', name: 'Starfield', description: 'Dark silver foil containing sparse fixed starbursts and a separate fine population of angular microfacets.',
    diffraction: { period: 1.8, bandwidth: .042, strength: 1.6, crossWidth: .36, secondaryOrder: .25 },
    structure: { field: 'starfield', scale: 27, engraving: .1, relief: .015, facetTilt: .7 },
    glints: { density: .18, scale: 390, sharpness: 330, strength: 24 },
    surface: { roughness: .24, metalness: .8, laminateRoughness: .19 },
  }),
  original({ id: 'topography', name: 'Holographic topography', description: 'Nested contour engravings with local slope-controlled diffraction and reflective shallow ridges.',
    diffraction: { period: 1.25, bandwidth: .028, strength: 1.5, crossWidth: .27, secondaryOrder: .06 },
    structure: { field: 'contour', scale: 42, engraving: .4, relief: .06, facetTilt: .25, patternRelief: .6, normalVariance: .15 },
    glints: { density: .025, strength: 4 }, surface: { roughness: .27, metalness: .72 },
  }),
];
