import type { HolographicProfile } from '../HolographicProfile';

/** Optical reconstructions stay in development until compared against moving, multi-light references. */
export const pokemonProfiles: HolographicProfile[] = [{
  id: 'pokemon-rainbow-etched', name: 'Rainbow Rare · Etched', family: 'Pokémon', status: 'reference-pending',
  description: 'Sword & Shield Rainbow Rare: fine engraved full-card foil, directional body striae, granular backing and shallow silhouette relief. Card-authored maps register the grating and surface to the print; reflected wavelengths follow the light, view and etched normals.',
  diffraction: { period: 1.18, bandwidth: .048, strength: .36, secondaryOrder: .14, direction: 0, crossWidth: .48, facetCoupling: 0 },
  structure: { field: 'plain', scale: 1, engraving: 0, relief: .1, facetTilt: 0, normalVariance: .35 },
  glints: { density: .24, scale: 820, sharpness: 220, strength: 7, spread: .65 },
  surface: { metalness: .72, roughness: .38, laminate: .07, laminateRoughness: .38, foilReflectance: .028, varnishRelief: .06, substrateDarkening: .10 },
}, {
  id: 'pokemon-ex-energy', name: 'EX Energy symbols', family: 'Pokémon', status: 'reference-pending',
  description: 'FireRed & LeafGreen-style varied energy symbols with independently inclined optical cells. A printing supplies its picture coverage and any separate rules stamp; the symbols are etched foil geometry, not colored decals.',
  diffraction: { period: 1.22, bandwidth: .042, strength: 1.5, secondaryOrder: .12, direction: 0, crossWidth: .42, facetCoupling: 1 },
  structure: { field: 'symbol-foil', scale: 31, engraving: .06, relief: 0, patternRelief: .035, facetTilt: 1.1, reflectionCoupling: .40, normalVariance: .2,
    motif: { symbols: ['water', 'fire', 'grass', 'lightning', 'psychic', 'fighting', 'darkness', 'metal', 'colorless'], arrangement: 'scattered', size: .36, smallScale: .55, rotation: 0, curvature: 0 } },
  glints: { density: .01, scale: 690, sharpness: 300, strength: 1, spread: .3 },
  surface: { metalness: .78, roughness: .33, patternRoughness: -.075, laminate: .17, laminateRoughness: .35, foilReflectance: .10, sheen: 0 },
}, {
  id: 'pokemon-ex-emerald', name: 'EX Poké Ball / stars', family: 'Pokémon', status: 'reference-pending',
  description: 'Emerald-style flat Poké Ball outlines interspersed with fine radial stars. Optical inclinations reveal different portions as the card tilts. The selected printing supplies independent picture, subject and stamp masks.',
  diffraction: { period: 1.25, bandwidth: .043, strength: 1.55, secondaryOrder: .14, direction: 0, crossWidth: .44, facetCoupling: 1 },
  structure: { field: 'symbol-foil', scale: 13, engraving: .06, relief: 0, patternRelief: .02, facetTilt: 1.15, reflectionCoupling: .35, normalVariance: .2,
    motif: { symbols: ['ball', 'ball', 'star'], arrangement: 'scattered', size: .36, smallScale: .53, rotation: 0, curvature: .3 } },
  glints: { density: .02, scale: 740, sharpness: 320, strength: 1.4, spread: .38 },
  surface: { metalness: .79, roughness: .32, patternRoughness: -.06, laminate: .17, laminateRoughness: .35, foilReflectance: .10, sheen: .03 },
}, {
  id: 'pokemon-legendary-reverse', name: 'Legendary reverse', family: 'Pokémon', status: 'reference-pending',
  description: 'Legendary Collection reverse: large overlapping radial fields composed of dense, fine broken foil cuts. Local fragments exchange spectral and silver reflections above the body and border; printed letters retain their own protection.',
  diffraction: { period: 1.29, bandwidth: .043, strength: 2.8, secondaryOrder: .12, direction: 0, crossWidth: .41, facetCoupling: 1 },
  structure: { field: 'legendary-fireworks', scale: 4.7, engraving: .08, relief: 0, facetTilt: 1.35, reflectionCoupling: .55, normalVariance: .4 },
  glints: { density: .009, scale: 760, sharpness: 310, strength: 1.2, spread: .40 },
  surface: { metalness: .82, roughness: .27, laminate: .18, laminateRoughness: .32, foilReflectance: .08, sheen: 0 },
}, {
  id: 'pokemon-e-reader', name: 'E-reader reverse', family: 'Pokémon', status: 'reference-pending',
  description: 'Early reverse foil: a nearly planar metallic sheet beneath body ink, with subtle directional grain and broad light-selected spectral reflections. The card supplies an explicit reverse mask protecting artwork and e-reader rails.',
  diffraction: { period: 1.12, bandwidth: .065, strength: .63, secondaryOrder: .06, direction: 0, crossWidth: .46, facetCoupling: 1 },
  structure: { field: 'e-reader', scale: 850, reflectionCoupling: .25, engraving: .025, relief: 0, facetTilt: .85, normalVariance: .18 },
  glints: { density: 0, scale: 720, sharpness: 310, strength: 0, spread: .16 },
  surface: { metalness: .64, roughness: .32, laminate: .12, laminateRoughness: .42, foilReflectance: .045, sheen: 0 },
}, {
  id: 'pokemon-cracked-ice', name: 'Cracked Ice', family: 'Pokémon', status: 'reference-pending',
  description: 'Broad irregular triangular facets with independent silver and spectral reflections. Fine grain lies within each unraised facet; opaque printed subjects retain their card-authored masks.',
  diffraction: { period: 1.13, bandwidth: .045, strength: .80, secondaryOrder: .09, direction: 0, crossWidth: .38, facetCoupling: 1 },
  structure: { field: 'cracked-ice', scale: 19, engraving: .05, relief: 0, facetTilt: 1.05, reflectionCoupling: .55, normalVariance: .34 },
  glints: { density: .006, scale: 700, sharpness: 330, strength: .9, spread: .24 },
  surface: { metalness: .80, roughness: .29, laminate: .20, laminateRoughness: .30, foilReflectance: .13, sheen: .06 },
}, {
  id: 'pokemon-sequin', name: 'Sequin', family: 'Pokémon', status: 'reference-pending',
  description: 'General Mills-style faceted rings, small rosettes and stepped square motifs. Their fixed radial optical cells select different highlights during tilt.',
  diffraction: { period: 1.20, bandwidth: .041, strength: 1.35, secondaryOrder: .09, direction: 0, crossWidth: .40, facetCoupling: 1 },
  structure: { field: 'sequin', scale: 37, engraving: .05, relief: 0, facetTilt: 1.1, reflectionCoupling: .65, normalVariance: .38 },
  glints: { density: .012, scale: 670, sharpness: 330, strength: 1.0, spread: .28 },
  surface: { metalness: .82, roughness: .25, laminate: .19, laminateRoughness: .31, foilReflectance: .14, sheen: .12 },
}, {
  id: 'pokemon-pixel', name: 'Pixel / Confetti', family: 'Pokémon', status: 'reference-pending',
  description: 'McDonald’s-style clustered blocky foil flakes, also called Pixel. Small square cuts share broader sheet inclinations and retain neutral silver among the colored flashes.',
  diffraction: { period: 1.20, bandwidth: .043, strength: 1.25, secondaryOrder: .10, direction: 0, crossWidth: .42, facetCoupling: 1 },
  structure: { field: 'confetti', scale: 175, engraving: .07, relief: 0, facetTilt: 1.15, reflectionCoupling: .50, normalVariance: .45 },
  glints: { density: .018, scale: 640, sharpness: 310, strength: 1.3, spread: .26 },
  surface: { metalness: .83, roughness: .27, laminate: .18, laminateRoughness: .32, foilReflectance: .13, sheen: .10 },
}, {
  id: 'pokemon-speckle', name: 'Speckle', family: 'Pokémon', status: 'reference-pending',
  description: 'Dense isolated fine points, substantially smaller than Confetti flakes. Each fixed point has its own inclination within a restrained directional spectral field.',
  diffraction: { period: 1.22, bandwidth: .045, strength: 1.2, secondaryOrder: .09, direction: 0, crossWidth: .42, facetCoupling: 1 },
  structure: { field: 'speckle', scale: 590, engraving: .06, relief: 0, facetTilt: 1.0, reflectionCoupling: .40, normalVariance: .55 },
  glints: { density: .025, scale: 800, sharpness: 310, strength: 1.25, spread: .24 },
  surface: { metalness: .79, roughness: .28, laminate: .19, laminateRoughness: .32, foilReflectance: .12, sheen: .10 },
}, {
  id: 'pokemon-sheen', name: 'Sheen', family: 'Pokémon', status: 'reference-pending',
  description: 'XY international-style continuous diagonal reflective bands with very fine striae. Smooth silver foil between spectral reflections; card-authored coverage preserves the print.',
  diffraction: { period: 1.22, bandwidth: .060, strength: .58, secondaryOrder: .09, direction: 0, crossWidth: .45, facetCoupling: 1 },
  structure: { field: 'sheen', scale: 700, reflectionCoupling: .12, engraving: .04, relief: 0, facetTilt: .85, normalVariance: .25 },
  glints: { density: .001, scale: 720, sharpness: 310, strength: .3, spread: .18 },
  surface: { metalness: .76, roughness: .28, laminate: .22, laminateRoughness: .30, foilReflectance: .08, sheen: 0 },
}, {
  id: 'pokemon-water-web', name: 'Water-Web', family: 'Pokémon', status: 'reference-pending',
  description: 'Sun & Moon-style broad curved wave reflections, with a continuous grating following the local sheet inclination. Fine backing grain without engraved contour lines.',
  diffraction: { period: 1.24, bandwidth: .065, strength: .66, secondaryOrder: .11, direction: 0, crossWidth: .47, facetCoupling: 1 },
  structure: { field: 'water-web', scale: 650, reflectionCoupling: .14, engraving: .07, relief: 0, facetTilt: .90, normalVariance: .30 },
  glints: { density: .003, scale: 720, sharpness: 300, strength: .55, spread: .22 },
  surface: { metalness: .78, roughness: .28, laminate: .22, laminateRoughness: .30, foilReflectance: .09, sheen: 0 },
}, {
  id: 'pokemon-vertical-line', name: 'Line', family: 'Pokémon', status: 'reference-pending',
  description: 'Sword & Shield-style unequal fine vertical cuts with top-to-bottom optical selection. Individual columns retain silver highlights while shared spectral bands change with tilt.',
  diffraction: { period: 1.18, bandwidth: .037, strength: 1.9, secondaryOrder: .10, direction: 0, crossWidth: .44, facetCoupling: 1 },
  structure: { field: 'vertical-line', scale: 310, engraving: .10, relief: 0, facetTilt: .95, normalVariance: .40 },
  glints: { density: .009, scale: 700, sharpness: 340, strength: 1.1, spread: .20 },
  surface: { metalness: .84, roughness: .25, laminate: .18, laminateRoughness: .32, foilReflectance: .21, sheen: .44 },
}, {
  id: 'pokemon-mirage', name: 'Mirage', family: 'Pokémon', status: 'reference-pending', extendedCoverage: true,
  description: 'Scarlet & Violet-style polished horizontal reflective bands and fine horizontal grain. The matched card supplies a separate silver-border mask; rules and opaque artwork stay printed.',
  diffraction: { period: 1.17, bandwidth: .057, strength: .54, secondaryOrder: .08, direction: 0, crossWidth: .42, facetCoupling: 1 },
  structure: { field: 'mirage', scale: 940, reflectionCoupling: .10, engraving: .035, relief: 0, facetTilt: .90, normalVariance: .24 },
  glints: { density: .001, scale: 780, sharpness: 340, strength: .25, spread: .16 },
  surface: { metalness: .81, roughness: .25, laminate: .20, laminateRoughness: .31, foilReflectance: .09, sheen: 0 },
}, {
  id: 'pokemon-fireworks', name: 'Fireworks', family: 'Pokémon', status: 'reference-pending',
  description: 'Legendary Collection-inspired bursts of broken radial foil cuts, with independently flashing silver fragments and curved spectral fans. Uses the selected card’s authored foil coverage.',
  diffraction: { period: 1.35, bandwidth: .047, strength: 2.5, secondaryOrder: .19, direction: 0, crossWidth: .46, facetCoupling: 1 },
  structure: { field: 'fireworks', scale: 8.2, engraving: .10, relief: 0, facetTilt: 1, normalVariance: .40 },
  glints: { density: .018, scale: 560, sharpness: 260, strength: 2, spread: .48 },
  surface: { metalness: .86, roughness: .26, laminate: .22, laminateRoughness: .28, foilReflectance: .20, sheen: .30 },
}, {
  id: 'pokemon-crosshatch', name: 'Crosshatch', family: 'Pokémon', status: 'reference-pending',
  description: 'League-style fine diagonal microcuts grouped into crossed reflective bands; silver woven highlights exchange with two diffractive axes under tilt.',
  diffraction: { period: 1.24, bandwidth: .046, strength: 2.3, secondaryOrder: .12, direction: 0, crossWidth: .42, crossing: .46, facetCoupling: 1 },
  structure: { field: 'crosshatch', scale: 270, engraving: .12, relief: 0, facetTilt: 1, normalVariance: .40 },
  glints: { density: .008, scale: 580, sharpness: 300, strength: 1.2, spread: .24 },
  surface: { metalness: .82, roughness: .29, laminate: .20, laminateRoughness: .30, foilReflectance: .18, sheen: .26 },
}, {
  id: 'pokemon-ace-spec', name: 'ACE SPEC', family: 'Pokémon', status: 'reference-pending',
  description: 'Modern Scarlet & Violet ACE SPEC: broad diamond reflections above dense horizontal striations. The printed card supplies its ink colors; the foil remains silver and spectral.',
  diffraction: { period: 1.15, bandwidth: .052, strength: 1.85, secondaryOrder: .12, direction: 0, crossWidth: .45, facetCoupling: 1 },
  structure: { field: 'ace-spec', scale: 440, engraving: .10, relief: 0, facetTilt: .90, normalVariance: .42 },
  glints: { density: .005, scale: 610, sharpness: 280, strength: .8, spread: .20 },
  surface: { metalness: .83, roughness: .30, laminate: .24, laminateRoughness: .28, foilReflectance: .19, sheen: .26 },
}, {
  id: 'pokemon-base-set-star', name: 'Star Holo: Base Set', family: 'Pokémon', status: 'reference-pending',
  description: 'Original English Base Set sheet: narrow unequal eight-ray starbursts with compact cores, occasional thin long-ray flashes and pinpoints over horizontal foil grain. Guided by the actual card fronts and moving references. Stars and backing respond to light and viewing angle.',
  diffraction: { period: 1.25, bandwidth: .085, strength: .78, secondaryOrder: .06, direction: 0, crossWidth: .52, facetCoupling: 1 },
  structure: { field: 'base-set-star', scale: 16, engraving: 0, relief: 0, facetTilt: 1, reflectionCoupling: .14, normalVariance: .18 },
  glints: { density: .004, scale: 560, sharpness: 180, strength: .75, spread: .45 },
  surface: { metalness: .72, roughness: .34, laminate: .20, laminateRoughness: .34, foilReflectance: .15, sheen: .48, inkTransmission: .48 },
}, {
  id: 'pokemon-galaxy-star', name: 'Starlight / Galaxy-Star', family: 'Pokémon', status: 'reference-pending',
  description: 'Early star sheet: sparse four- and eight-point stars, small pinpoints and coherent angular facets over a quiet spectral background.',
  diffraction: { period: 1.4, bandwidth: .055, strength: 2.1, secondaryOrder: .2, direction: 0, crossWidth: .50 },
  structure: { field: 'galaxy-star', scale: 15, engraving: .04, relief: 0, facetTilt: .8, normalVariance: .25 },
  glints: { density: .065, scale: 420, sharpness: 210, strength: 10, spread: .6 },
  surface: { metalness: .88, roughness: .27, laminate: .25, laminateRoughness: .30, foilReflectance: .16 },
}, {
  id: 'pokemon-tinsel', name: 'Tinsel', family: 'Pokémon', status: 'reference-pending',
  description: 'Thin uneven horizontal silver strands, broken spectral flashes and correlated angular reflections.',
  diffraction: { period: 1.15, bandwidth: .04, strength: 1.8, secondaryOrder: .12, direction: 0, crossWidth: .44, facetCoupling: 1 },
  structure: { field: 'tinsel', scale: 174, engraving: .08, relief: 0, facetTilt: 1.15, normalVariance: .45 },
  glints: { density: .025, scale: 640, sharpness: 340, strength: 3, spread: .20 },
  surface: { metalness: .84, roughness: .26, laminate: .18, laminateRoughness: .32, foilReflectance: .30, anisotropy: .35, sheen: .95 },
}, {
  id: 'pokemon-cosmos', name: 'Cosmos', family: 'Pokémon', status: 'reference-pending',
  description: 'Classic pixelated Cosmos: unequal circles, rosettes and a broken swirl made from small independently oriented optical cells.',
  diffraction: { period: 1.45, bandwidth: .055, strength: 1.7, secondaryOrder: .24, direction: 0, crossWidth: .42 },
  structure: { field: 'cosmos', scale: 29, engraving: .05, relief: 0, facetTilt: .9 },
  glints: { density: .22, scale: 390, sharpness: 180, strength: 30, spread: .72 },
  surface: { metalness: .88, roughness: .18, laminate: .35, laminateRoughness: .22, foilReflectance: .32 },
}, {
  id: 'pokemon-cosmos-hd', name: 'Cosmos HD', family: 'Pokémon', status: 'reference-pending',
  description: 'Later smooth-sheet Cosmos: solid circular symbols and an unbroken swirl with coherent color within each shape. No rosettes or classic pixel fragmentation.',
  diffraction: { period: 1.45, bandwidth: .045, strength: 1.35, secondaryOrder: .18, direction: 0, crossWidth: .38 },
  structure: { field: 'cosmos-hd', scale: 29, engraving: .05, relief: 0, facetTilt: .7 },
  glints: { density: .055, scale: 410, sharpness: 240, strength: 10, spread: .5 },
  surface: { metalness: .88, roughness: .2, laminate: .35, laminateRoughness: .22, foilReflectance: .32 },
}];
