/** Exact English masters and two independently maintained checklist snapshots. */
import { mkdir, readFile, writeFile, access } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const base = 'public/cards/pokemon/aquapolis';
await mkdir(base, {recursive:true});
const exists = p => access(p).then(()=>true,()=>false);
async function bytes(url) {
  for(let i=0;;i++) {
    try { const r=await fetch(url,{signal:AbortSignal.timeout(30000)}); if(!r.ok) throw Error(`${r.status} ${url}`); return Buffer.from(await r.arrayBuffer()); }
    catch(e) { if(i===4||e.message.startsWith('404')) throw e; await new Promise(r=>setTimeout(r,500*2**i)); }
  }
}
async function limited(items,fn) {
  const result=new Array(items.length); let cursor=0;
  await Promise.all(Array.from({length:6},async()=>{while(cursor<items.length){const i=cursor++;result[i]=await fn(items[i],i);}}));
  return result;
}
const set=JSON.parse(await readFile('research/aquapolis/set.json','utf8'));
const independent=JSON.parse(await readFile('research/aquapolis/checklist-independent.json','utf8'));
if(set.cards.length!==186||set.cardCount.official!==147) throw Error('Unexpected checklist');
const cards=await limited(set.cards,async brief=>{
  const cache=`research/aquapolis/${brief.id}.json`;
  const card=JSON.parse(await exists(cache)?await readFile(cache,'utf8'):await bytes(`https://api.tcgdex.net/v2/en/cards/${brief.id}`));
  if(card.id!==brief.id) throw Error(`Bad metadata ${brief.id}`);
  const {id,localId,name,category,stage,evolveFrom,types,trainerType,energyType,image,variants}=card;
  await writeFile(cache,JSON.stringify(card,null,2)+'\n');
  const number=localId.startsWith('H')?`H${Number(localId.slice(1))}`:localId;
  const peer=independent.find(c=>c.number===(/[ab]$/.test(number)?number.slice(0,-1):number));
  if(!peer||peer.name!==name) throw Error(`Checklist disagreement ${id} ${name}`);
  const rarity=peer.rarity==='Rare Holo'?'Holo Rare':peer.rarity==='Rare Secret'?'Secret Rare':peer.rarity;
  return {id,localId:number,name,category,rarity,stage,evolveFrom,types,trainerType,energyType,image,variants};
});
const sources=await limited(cards,async (card,i)=>{
  const file=`${card.localId}.png`, target=`${base}/${file}`;
  // Neither checklist CDN exposes exact a/b filenames. Their unsuffixed scans are a prints.
  const bProducts={'50b':85814,'74b':84972,'95b':87591,'103b':88307};
  if(card.localId in bProducts) {
    const url=`https://tcgplayer-cdn.tcgplayer.com/product/${bProducts[card.localId]}_in_1000x1000.jpg`;
    const raw=`research/aquapolis/${card.localId}-source.jpg`;
    if(!await exists(raw))await writeFile(raw,await bytes(url));
    // Decode/re-encode losslessly to PNG offline; never enlarge a low-resolution source.
    const {execFileSync}=await import('node:child_process');
    execFileSync(process.env.PYTHON ?? 'python',['-c',`from PIL import Image; Image.open('${raw}').convert('RGB').save('${target}')`]);
    const data=await readFile(target);
    return {cardId:card.id,file,url,width:data.readUInt32BE(16),height:data.readUInt32BE(20),sha256:createHash('sha256').update(data).digest('hex'),sourceSha256:createHash('sha256').update(await readFile(raw)).digest('hex'),quality:'Exact b-print stock image; only 200px wide available. Replacement with higher-resolution exact-print scan remains desirable.',transform:'JPEG decode to PNG; no resize/crop/flip'};
  }
  const sourceNumber=card.localId.endsWith('a')?card.localId.slice(0,-1):card.localId;
  const urls=[`https://images.pokemontcg.io/ecard2/${sourceNumber}_hires.png`,...(card.image?[`${card.image}/high.png`]:[])];
  let url=urls[0];
  if(!await exists(target)) {
    let data;
    for(const candidate of urls) { try {data=await bytes(candidate);url=candidate;break;}catch(e){if(candidate===urls.at(-1)&&!/[ab]$/.test(card.localId))throw e;} }
    if(!data)throw Error(`Missing exact image: ${card.localId}`);
    await writeFile(target,data);
  }
  const data=await readFile(target);
  if(data.subarray(0,8).toString('hex')!=='89504e470d0a1a0a')throw Error(`Invalid PNG ${file}`);
  if((i+1)%25===0)console.log(`Masters ${i+1}/186`);
  return {cardId:card.id,url,file,width:data.readUInt32BE(16),height:data.readUInt32BE(20),sha256:createHash('sha256').update(data).digest('hex'),role:'untouched-English-full-card-master'};
});
await writeFile(`${base}/sources.json`,JSON.stringify(sources,null,2)+'\n');
await writeFile(`${base}/catalog.json`,JSON.stringify({id:'ecard2',name:'Aquapolis',releaseDate:'2003-01-15',printedTotal:147,total:186,cards},null,2)+'\n');
const records=cards.map(({image,variants,...card},i)=>({...card,front:sources[i].file}));
await writeFile('src/pokemon/data/aquapolis.generated.ts','// Generated by scripts/aquapolis/fetch-catalog.mjs; raw metadata and source hashes are preserved.\nexport const aquapolisRecords = [\n'+records.map(c=>'  '+JSON.stringify(c)+',').join('\n')+'\n] as const;\n');
console.log('Saved 186 checklist entries and English PNG masters (four b prints have lower-resolution stock sources).');
