import type { ArtifactDefinition } from './types';
export const artifacts: ArtifactDefinition[] = [{
  id: 'robotic-bird', name: 'Robotic bird', subtitle: '01 / Electromechanical specimen',
  description: 'A transparent anatomy of circuits, wire and precision mechanics.',
  thumbnail: `${import.meta.env?.BASE_URL ?? '/'}artifacts/robotic-bird-preview.png`,
  camera: { position: [3.75, 1.55, 8.35], target: [-.10, .10, 0] }, lighting: 'Studio',
  capabilities: { rotate: true, zoom: true, lighting: true, movableLight: true, fullscreen: true, exploded: true, inspection: true },
  inspection: ['clear', 'frosted', 'hidden'],
  explodedGroups: [
    { id: 'shell-front', label: 'Front shell', offset: [0, .15, 1.65] },
    { id: 'shell-back', label: 'Rear shell', offset: [0, .15, -1.65] },
    { id: 'shell-dorsal', label: 'Dorsal shell', offset: [-.2, 1.45, 0] },
    { id: 'shell-belly', label: 'Belly shell', offset: [.1, -.9, .7] },
    { id: 'head', label: 'Head shell & beak', offset: [.7, 1.25, 0] },
    { id: 'head-electronics', label: 'Camera & head electronics', offset: [.6, .45, .4] },
    { id: 'wing-front', label: 'Near wing', offset: [-.4, .4, 2.4] },
    { id: 'wing-back', label: 'Far wing', offset: [-.4, .4, -2.4] },
    { id: 'tail', label: 'Tail', offset: [-1.3, -.15, 0] },
    { id: 'boards', label: 'Circuit boards', offset: [.1, .65, .75] },
    { id: 'boards-back', label: 'Reverse-side electronics', offset: [.3, .6, -1.05] },
    { id: 'boards-core', label: 'Internal circuit shelves', offset: [-.5, .4, -.2] },
    { id: 'mechanics', label: 'Drive train', offset: [0, -.45, -.75] },
    { id: 'wires', label: 'Wire harness', offset: [-.4, 1.1, -.2] },
    { id: 'wires-back', label: 'Reverse-side harness', offset: [-.7, .9, -.75] },
    { id: 'legs', label: 'Leg assemblies', offset: [.15, -1.15, .15] },
  ],
  load: async signal => { const { buildBird } = await import('./RoboticBird'); signal.throwIfAborted(); return buildBird(); },
}, {
  id: 'melee-disc', name: 'Super Smash Bros. Melee', subtitle: '02 / Nintendo GameCube · Optical disc',
  description: 'Printed ink, clear polycarbonate and a concentric optical data layer.',
  thumbnail: `${import.meta.env?.BASE_URL ?? '/'}artifacts/melee/front.png`,
  camera: { position: [0, .15, 10.8], target: [0, 0, 0] }, lighting: 'Studio',
  capabilities: { rotate: true, zoom: true, lighting: true, movableLight: true, fullscreen: true, exploded: false, inspection: false },
  inspection: [], explodedGroups: [],
  load: async signal => { const { loadMeleeDisc } = await import('./MeleeDisc'); return loadMeleeDisc(signal); },
}];
