// Generated by scripts/fetch-wizards-promos.mjs from TCGdex.
export const wizardsPromoRecords = [
  {
    "id": "basep-1",
    "localId": "1",
    "name": "Pikachu",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Lightning"
    ],
    "front": "1.png"
  },
  {
    "id": "basep-6",
    "localId": "6",
    "name": "Arcanine",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Stage1",
    "evolveFrom": "Growlithe",
    "types": [
      "Fire"
    ],
    "front": "6.png"
  },
  {
    "id": "basep-7",
    "localId": "7",
    "name": "Jigglypuff",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Colorless"
    ],
    "front": "7.png"
  },
  {
    "id": "basep-8",
    "localId": "8",
    "name": "Mew",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Psychic"
    ],
    "front": "8.png"
  },
  {
    "id": "basep-12",
    "localId": "12",
    "name": "Mewtwo",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Psychic"
    ],
    "front": "12.png"
  },
  {
    "id": "basep-14",
    "localId": "14",
    "name": "Mewtwo",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Psychic"
    ],
    "front": "14.png"
  },
  {
    "id": "basep-16",
    "localId": "16",
    "name": "Computer Error",
    "rarity": "Common",
    "category": "Trainer",
    "front": "16.png"
  },
  {
    "id": "basep-19",
    "localId": "19",
    "name": "Sabrina's Abra",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Psychic"
    ],
    "front": "19.png"
  },
  {
    "id": "basep-20",
    "localId": "20",
    "name": "Psyduck",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Water"
    ],
    "front": "20.png"
  },
  {
    "id": "basep-21",
    "localId": "21",
    "name": "Moltres",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Fire"
    ],
    "front": "21.png"
  },
  {
    "id": "basep-22",
    "localId": "22",
    "name": "Articuno",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Water"
    ],
    "front": "22.png"
  },
  {
    "id": "basep-23",
    "localId": "23",
    "name": "Zapdos",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Lightning"
    ],
    "front": "23.png"
  },
  {
    "id": "basep-25",
    "localId": "25",
    "name": "Flying Pikachu",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Lightning"
    ],
    "front": "25.png"
  },
  {
    "id": "basep-26",
    "localId": "26",
    "name": "Pikachu",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Lightning"
    ],
    "front": "26.png"
  },
  {
    "id": "basep-27",
    "localId": "27",
    "name": "Pikachu",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Lightning"
    ],
    "front": "27.png"
  },
  {
    "id": "basep-28",
    "localId": "28",
    "name": "Surfing Pikachu",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Lightning"
    ],
    "front": "28.png"
  },
  {
    "id": "basep-29",
    "localId": "29",
    "name": "Marill",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Water"
    ],
    "front": "29.png"
  },
  {
    "id": "basep-30",
    "localId": "30",
    "name": "Togepi",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Colorless"
    ],
    "front": "30.png"
  },
  {
    "id": "basep-31",
    "localId": "31",
    "name": "Cleffa",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Colorless"
    ],
    "front": "31.png"
  },
  {
    "id": "basep-32",
    "localId": "32",
    "name": "Smeargle",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Colorless"
    ],
    "front": "32.png"
  },
  {
    "id": "basep-36",
    "localId": "36",
    "name": "Igglybuff",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Colorless"
    ],
    "front": "36.png"
  },
  {
    "id": "basep-37",
    "localId": "37",
    "name": "Hitmontop",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Fighting"
    ],
    "front": "37.png"
  },
  {
    "id": "basep-38",
    "localId": "38",
    "name": "Unown [J]",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Psychic"
    ],
    "front": "38.png"
  },
  {
    "id": "basep-39",
    "localId": "39",
    "name": "Misdreavus",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Psychic"
    ],
    "front": "39.png"
  },
  {
    "id": "basep-40",
    "localId": "40",
    "name": "Pokémon Center",
    "rarity": "Common",
    "category": "Trainer",
    "front": "40.png"
  },
  {
    "id": "basep-41",
    "localId": "41",
    "name": "Lucky Stadium",
    "rarity": "Common",
    "category": "Trainer",
    "front": "41.png"
  },
  {
    "id": "basep-42",
    "localId": "42",
    "name": "Pokémon Tower",
    "rarity": "Common",
    "category": "Trainer",
    "front": "42.png"
  },
  {
    "id": "basep-43",
    "localId": "43",
    "name": "Machamp",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Stage2",
    "evolveFrom": "Machoke",
    "types": [
      "Fighting"
    ],
    "front": "43.png"
  },
  {
    "id": "basep-44",
    "localId": "44",
    "name": "Magmar",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Fire"
    ],
    "front": "44.png"
  },
  {
    "id": "basep-45",
    "localId": "45",
    "name": "Scyther",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Grass"
    ],
    "front": "45.png"
  },
  {
    "id": "basep-46",
    "localId": "46",
    "name": "Electabuzz",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Lightning"
    ],
    "front": "46.png"
  },
  {
    "id": "basep-47",
    "localId": "47",
    "name": "Mew",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Psychic"
    ],
    "front": "47.png"
  },
  {
    "id": "basep-48",
    "localId": "48",
    "name": "Articuno",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Water"
    ],
    "front": "48.png"
  },
  {
    "id": "basep-49",
    "localId": "49",
    "name": "Snorlax",
    "rarity": "Common",
    "category": "Pokemon",
    "stage": "Basic",
    "types": [
      "Colorless"
    ],
    "front": "49.png"
  }
] as const;
