// Generated by scripts/fetch-non-holo-expansion.mjs.
export const nonHoloExpansionCatalog = [
  {
    "family": "pokemon",
    "slug": "sv1-hypno-83",
    "title": "Hypno",
    "set": "Scarlet & Violet · Uncommon",
    "number": "83"
  },
  {
    "family": "pokemon",
    "slug": "sv1-ralts-84",
    "title": "Ralts",
    "set": "Scarlet & Violet · Common",
    "number": "84"
  },
  {
    "family": "pokemon",
    "slug": "sv1-kirlia-85",
    "title": "Kirlia",
    "set": "Scarlet & Violet · Common",
    "number": "85"
  },
  {
    "family": "pokemon",
    "slug": "sv1-shuppet-87",
    "title": "Shuppet",
    "set": "Scarlet & Violet · Common",
    "number": "87"
  },
  {
    "family": "pokemon",
    "slug": "sv1-drifloon-89",
    "title": "Drifloon",
    "set": "Scarlet & Violet · Common",
    "number": "89"
  },
  {
    "family": "pokemon",
    "slug": "sv1-drifblim-90",
    "title": "Drifblim",
    "set": "Scarlet & Violet · Uncommon",
    "number": "90"
  },
  {
    "family": "pokemon",
    "slug": "sv1-flabebe-91",
    "title": "Flabébé",
    "set": "Scarlet & Violet · Common",
    "number": "91"
  },
  {
    "family": "pokemon",
    "slug": "sv1-floette-92",
    "title": "Floette",
    "set": "Scarlet & Violet · Common",
    "number": "92"
  },
  {
    "family": "pokemon",
    "slug": "sv1-florges-93",
    "title": "Florges",
    "set": "Scarlet & Violet · Uncommon",
    "number": "93"
  },
  {
    "family": "pokemon",
    "slug": "sv1-dedenne-94",
    "title": "Dedenne",
    "set": "Scarlet & Violet · Common",
    "number": "94"
  },
  {
    "family": "pokemon",
    "slug": "sv1-fidough-97",
    "title": "Fidough",
    "set": "Scarlet & Violet · Common",
    "number": "97"
  },
  {
    "family": "pokemon",
    "slug": "sv1-dachsbun-99",
    "title": "Dachsbun",
    "set": "Scarlet & Violet · Uncommon",
    "number": "99"
  },
  {
    "family": "pokemon",
    "slug": "sv1-flittle-100",
    "title": "Flittle",
    "set": "Scarlet & Violet · Common",
    "number": "100"
  },
  {
    "family": "pokemon",
    "slug": "sv1-espathra-103",
    "title": "Espathra",
    "set": "Scarlet & Violet · Uncommon",
    "number": "103"
  },
  {
    "family": "pokemon",
    "slug": "sv1-greavard-104",
    "title": "Greavard",
    "set": "Scarlet & Violet · Common",
    "number": "104"
  },
  {
    "family": "pokemon",
    "slug": "sv1-meditite-110",
    "title": "Meditite",
    "set": "Scarlet & Violet · Common",
    "number": "110"
  },
  {
    "family": "pokemon",
    "slug": "sv1-medicham-111",
    "title": "Medicham",
    "set": "Scarlet & Violet · Uncommon",
    "number": "111"
  },
  {
    "family": "pokemon",
    "slug": "sv1-riolu-112",
    "title": "Riolu",
    "set": "Scarlet & Violet · Common",
    "number": "112"
  },
  {
    "family": "pokemon",
    "slug": "sv1-lucario-114",
    "title": "Lucario",
    "set": "Scarlet & Violet · Uncommon",
    "number": "114"
  },
  {
    "family": "pokemon",
    "slug": "sv1-sandile-115",
    "title": "Sandile",
    "set": "Scarlet & Violet · Common",
    "number": "115"
  },
  {
    "family": "pokemon",
    "slug": "sv1-krokorok-116",
    "title": "Krokorok",
    "set": "Scarlet & Violet · Common",
    "number": "116"
  },
  {
    "family": "pokemon",
    "slug": "sv1-krookodile-117",
    "title": "Krookodile",
    "set": "Scarlet & Violet · Uncommon",
    "number": "117"
  },
  {
    "family": "pokemon",
    "slug": "sv1-silicobra-119",
    "title": "Silicobra",
    "set": "Scarlet & Violet · Common",
    "number": "119"
  },
  {
    "family": "pokemon",
    "slug": "sv1-sandaconda-120",
    "title": "Sandaconda",
    "set": "Scarlet & Violet · Uncommon",
    "number": "120"
  },
  {
    "family": "pokemon",
    "slug": "sv1-stonjourner-121",
    "title": "Stonjourner",
    "set": "Scarlet & Violet · Uncommon",
    "number": "121"
  },
  {
    "family": "pokemon",
    "slug": "sv1-muk-127",
    "title": "Muk",
    "set": "Scarlet & Violet · Uncommon",
    "number": "127"
  },
  {
    "family": "pokemon",
    "slug": "sv1-seviper-128",
    "title": "Seviper",
    "set": "Scarlet & Violet · Common",
    "number": "128"
  },
  {
    "family": "pokemon",
    "slug": "sv1-spiritomb-129",
    "title": "Spiritomb",
    "set": "Scarlet & Violet · Uncommon",
    "number": "129"
  },
  {
    "family": "pokemon",
    "slug": "sv1-croagunk-130",
    "title": "Croagunk",
    "set": "Scarlet & Violet · Common",
    "number": "130"
  },
  {
    "family": "pokemon",
    "slug": "sv1-pawniard-132",
    "title": "Pawniard",
    "set": "Scarlet & Violet · Common",
    "number": "132"
  },
  {
    "family": "pokemon",
    "slug": "sv1-bisharp-133",
    "title": "Bisharp",
    "set": "Scarlet & Violet · Common",
    "number": "133"
  },
  {
    "family": "pokemon",
    "slug": "sv1-maschiff-135",
    "title": "Maschiff",
    "set": "Scarlet & Violet · Common",
    "number": "135"
  },
  {
    "family": "pokemon",
    "slug": "sv1-mabosstiff-137",
    "title": "Mabosstiff",
    "set": "Scarlet & Violet · Uncommon",
    "number": "137"
  },
  {
    "family": "pokemon",
    "slug": "sv1-bombirdier-138",
    "title": "Bombirdier",
    "set": "Scarlet & Violet · Uncommon",
    "number": "138"
  },
  {
    "family": "pokemon",
    "slug": "sv1-forretress-139",
    "title": "Forretress",
    "set": "Scarlet & Violet · Uncommon",
    "number": "139"
  },
  {
    "family": "pokemon",
    "slug": "sv1-varoom-140",
    "title": "Varoom",
    "set": "Scarlet & Violet · Common",
    "number": "140"
  },
  {
    "family": "pokemon",
    "slug": "sv1-blissey-145",
    "title": "Blissey",
    "set": "Scarlet & Violet · Uncommon",
    "number": "145"
  },
  {
    "family": "pokemon",
    "slug": "sv1-zangoose-146",
    "title": "Zangoose",
    "set": "Scarlet & Violet · Common",
    "number": "146"
  },
  {
    "family": "pokemon",
    "slug": "sv1-starly-148",
    "title": "Starly",
    "set": "Scarlet & Violet · Common",
    "number": "148"
  },
  {
    "family": "pokemon",
    "slug": "sv1-staravia-149",
    "title": "Staravia",
    "set": "Scarlet & Violet · Common",
    "number": "149"
  },
  {
    "family": "pokemon",
    "slug": "sv1-staraptor-150",
    "title": "Staraptor",
    "set": "Scarlet & Violet · Uncommon",
    "number": "150"
  },
  {
    "family": "pokemon",
    "slug": "sv1-skwovet-151",
    "title": "Skwovet",
    "set": "Scarlet & Violet · Common",
    "number": "151"
  },
  {
    "family": "pokemon",
    "slug": "sv1-greedent-152",
    "title": "Greedent",
    "set": "Scarlet & Violet · Uncommon",
    "number": "152"
  },
  {
    "family": "pokemon",
    "slug": "sv1-lechonk-154",
    "title": "Lechonk",
    "set": "Scarlet & Violet · Common",
    "number": "154"
  },
  {
    "family": "pokemon",
    "slug": "sv1-oinkologne-157",
    "title": "Oinkologne",
    "set": "Scarlet & Violet · Uncommon",
    "number": "157"
  },
  {
    "family": "pokemon",
    "slug": "sv1-tandemaus-159",
    "title": "Tandemaus",
    "set": "Scarlet & Violet · Common",
    "number": "159"
  },
  {
    "family": "pokemon",
    "slug": "sv1-maushold-161",
    "title": "Maushold",
    "set": "Scarlet & Violet · Uncommon",
    "number": "161"
  },
  {
    "family": "pokemon",
    "slug": "sv1-squawkabilly-162",
    "title": "Squawkabilly",
    "set": "Scarlet & Violet · Common",
    "number": "162"
  },
  {
    "family": "pokemon",
    "slug": "sv1-cyclizar-163",
    "title": "Cyclizar",
    "set": "Scarlet & Violet · Uncommon",
    "number": "163"
  },
  {
    "family": "pokemon",
    "slug": "sv1-flamigo-165",
    "title": "Flamigo",
    "set": "Scarlet & Violet · Uncommon",
    "number": "165"
  },
  {
    "family": "pokemon",
    "slug": "sv1-arven-166",
    "title": "Arven",
    "set": "Scarlet & Violet · Uncommon",
    "number": "166"
  },
  {
    "family": "pokemon",
    "slug": "sv1-beach-court-167",
    "title": "Beach Court",
    "set": "Scarlet & Violet · Uncommon",
    "number": "167"
  },
  {
    "family": "pokemon",
    "slug": "sv1-crushing-hammer-168",
    "title": "Crushing Hammer",
    "set": "Scarlet & Violet · Common",
    "number": "168"
  },
  {
    "family": "pokemon",
    "slug": "sv1-defiance-band-169",
    "title": "Defiance Band",
    "set": "Scarlet & Violet · Uncommon",
    "number": "169"
  },
  {
    "family": "pokemon",
    "slug": "sv1-electric-generator-170",
    "title": "Electric Generator",
    "set": "Scarlet & Violet · Uncommon",
    "number": "170"
  },
  {
    "family": "pokemon",
    "slug": "sv1-energy-retrieval-171",
    "title": "Energy Retrieval",
    "set": "Scarlet & Violet · Common",
    "number": "171"
  },
  {
    "family": "pokemon",
    "slug": "sv1-energy-search-172",
    "title": "Energy Search",
    "set": "Scarlet & Violet · Common",
    "number": "172"
  },
  {
    "family": "pokemon",
    "slug": "sv1-energy-switch-173",
    "title": "Energy Switch",
    "set": "Scarlet & Violet · Common",
    "number": "173"
  },
  {
    "family": "pokemon",
    "slug": "sv1-exp-share-174",
    "title": "Exp. Share",
    "set": "Scarlet & Violet · Uncommon",
    "number": "174"
  },
  {
    "family": "pokemon",
    "slug": "sv1-jacq-175",
    "title": "Jacq",
    "set": "Scarlet & Violet · Uncommon",
    "number": "175"
  },
  {
    "family": "pokemon",
    "slug": "sv1-judge-176",
    "title": "Judge",
    "set": "Scarlet & Violet · Uncommon",
    "number": "176"
  },
  {
    "family": "pokemon",
    "slug": "sv1-katy-177",
    "title": "Katy",
    "set": "Scarlet & Violet · Uncommon",
    "number": "177"
  },
  {
    "family": "pokemon",
    "slug": "sv1-mesagoza-178",
    "title": "Mesagoza",
    "set": "Scarlet & Violet · Uncommon",
    "number": "178"
  },
  {
    "family": "pokemon",
    "slug": "sv1-miriam-179",
    "title": "Miriam",
    "set": "Scarlet & Violet · Uncommon",
    "number": "179"
  },
  {
    "family": "pokemon",
    "slug": "sv1-nemona-180",
    "title": "Nemona",
    "set": "Scarlet & Violet · Common",
    "number": "180"
  },
  {
    "family": "pokemon",
    "slug": "sv1-nest-ball-181",
    "title": "Nest Ball",
    "set": "Scarlet & Violet · Uncommon",
    "number": "181"
  },
  {
    "family": "pokemon",
    "slug": "sv1-vitality-band-197",
    "title": "Vitality Band",
    "set": "Scarlet & Violet · Uncommon",
    "number": "197"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-actor-evil-heel-52240819",
    "title": "Abyss Actor - Evil Heel",
    "set": "Card Database · Non-holo stock",
    "number": "52240819"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-actor-extras-88412339",
    "title": "Abyss Actor - Extras",
    "set": "Card Database · Non-holo stock",
    "number": "88412339"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-actor-funky-comedian-99634927",
    "title": "Abyss Actor - Funky Comedian",
    "set": "Card Database · Non-holo stock",
    "number": "99634927"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-actor-hyper-director-2368215",
    "title": "Abyss Actor - Hyper Director",
    "set": "Card Database · Non-holo stock",
    "number": "2368215"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-actor-leading-lady-24907044",
    "title": "Abyss Actor - Leading Lady",
    "set": "Card Database · Non-holo stock",
    "number": "24907044"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-actor-liberty-dramatist-65477143",
    "title": "Abyss Actor - Liberty Dramatist",
    "set": "Card Database · Non-holo stock",
    "number": "65477143"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-actor-mellow-madonna-78310590",
    "title": "Abyss Actor - Mellow Madonna",
    "set": "Card Database · Non-holo stock",
    "number": "78310590"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-actor-sassy-rookie-51028231",
    "title": "Abyss Actor - Sassy Rookie",
    "set": "Card Database · Non-holo stock",
    "number": "51028231"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-actor-super-producer-47404795",
    "title": "Abyss Actor - Super Producer",
    "set": "Card Database · Non-holo stock",
    "number": "47404795"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-actor-superstar-25629622",
    "title": "Abyss Actor - Superstar",
    "set": "Card Database · Non-holo stock",
    "number": "25629622"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-actor-trendy-understudy-39024589",
    "title": "Abyss Actor - Trendy Understudy",
    "set": "Card Database · Non-holo stock",
    "number": "39024589"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-actor-twinkle-little-star-7279373",
    "title": "Abyss Actor - Twinkle Little Star",
    "set": "Card Database · Non-holo stock",
    "number": "7279373"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-actor-wild-hope-51391183",
    "title": "Abyss Actor - Wild Hope",
    "set": "Card Database · Non-holo stock",
    "number": "51391183"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-actors-back-stage-59057953",
    "title": "Abyss Actors Back Stage",
    "set": "Card Database · Non-holo stock",
    "number": "59057953"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-actors-curtain-call-4682617",
    "title": "Abyss Actors' Curtain Call",
    "set": "Card Database · Non-holo stock",
    "number": "4682617"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-actors-dress-rehearsal-6004133",
    "title": "Abyss Actors' Dress Rehearsal",
    "set": "Card Database · Non-holo stock",
    "number": "6004133"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-dweller-21044178",
    "title": "Abyss Dweller",
    "set": "Card Database · Non-holo stock",
    "number": "21044178"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-flower-40387124",
    "title": "Abyss Flower",
    "set": "Card Database · Non-holo stock",
    "number": "40387124"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-keeper-82184400",
    "title": "Abyss Keeper",
    "set": "Card Database · Non-holo stock",
    "number": "82184400"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-of-the-sacred-beasts-86132414",
    "title": "Abyss of the Sacred Beasts",
    "set": "Card Database · Non-holo stock",
    "number": "86132414"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-playhouse-fantastic-theater-77297908",
    "title": "Abyss Playhouse - Fantastic Theater",
    "set": "Card Database · Non-holo stock",
    "number": "77297908"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-prop-wild-wagon-86578200",
    "title": "Abyss Prop - Wild Wagon",
    "set": "Card Database · Non-holo stock",
    "number": "86578200"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-script-abysstainment-70564929",
    "title": "Abyss Script - Abysstainment",
    "set": "Card Database · Non-holo stock",
    "number": "70564929"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-script-dramatic-story-33503878",
    "title": "Abyss Script - Dramatic Story",
    "set": "Card Database · Non-holo stock",
    "number": "33503878"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-script-fantasy-magic-87390798",
    "title": "Abyss Script - Fantasy Magic",
    "set": "Card Database · Non-holo stock",
    "number": "87390798"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-script-fire-dragon-s-lair-50179591",
    "title": "Abyss Script - Fire Dragon's Lair",
    "set": "Card Database · Non-holo stock",
    "number": "50179591"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-script-opening-ceremony-23784496",
    "title": "Abyss Script - Opening Ceremony",
    "set": "Card Database · Non-holo stock",
    "number": "23784496"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-script-rise-of-the-abyss-king-13662809",
    "title": "Abyss Script - Rise of the Abyss King",
    "set": "Card Database · Non-holo stock",
    "number": "13662809"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-script-romantic-terror-41803903",
    "title": "Abyss Script - Romantic Terror",
    "set": "Card Database · Non-holo stock",
    "number": "41803903"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-shark-61496006",
    "title": "Abyss Shark",
    "set": "Card Database · Non-holo stock",
    "number": "61496006"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-soldier-18318842",
    "title": "Abyss Soldier",
    "set": "Card Database · Non-holo stock",
    "number": "18318842"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-stungray-97232518",
    "title": "Abyss Stungray",
    "set": "Card Database · Non-holo stock",
    "number": "97232518"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-warrior-88409165",
    "title": "Abyss Warrior",
    "set": "Card Database · Non-holo stock",
    "number": "88409165"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-scale-of-cetus-19596712",
    "title": "Abyss-scale of Cetus",
    "set": "Card Database · Non-holo stock",
    "number": "19596712"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-scale-of-the-kraken-8719957",
    "title": "Abyss-scale of the Kraken",
    "set": "Card Database · Non-holo stock",
    "number": "8719957"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-scale-of-the-mizuchi-72932673",
    "title": "Abyss-scale of the Mizuchi",
    "set": "Card Database · Non-holo stock",
    "number": "72932673"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-scorn-79206750",
    "title": "Abyss-scorn",
    "set": "Card Database · Non-holo stock",
    "number": "79206750"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-sphere-60202749",
    "title": "Abyss-sphere",
    "set": "Card Database · Non-holo stock",
    "number": "60202749"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-squall-34707034",
    "title": "Abyss-squall",
    "set": "Card Database · Non-holo stock",
    "number": "34707034"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-steam-63941169",
    "title": "Abyss-steam",
    "set": "Card Database · Non-holo stock",
    "number": "63941169"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-sting-triaina-81878201",
    "title": "Abyss-sting Triaina",
    "set": "Card Database · Non-holo stock",
    "number": "81878201"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyss-strom-97697447",
    "title": "Abyss-strom",
    "set": "Card Database · Non-holo stock",
    "number": "97697447"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyssal-designator-89801755",
    "title": "Abyssal Designator",
    "set": "Card Database · Non-holo stock",
    "number": "89801755"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyssal-kingshark-44223284",
    "title": "Abyssal Kingshark",
    "set": "Card Database · Non-holo stock",
    "number": "44223284"
  },
  {
    "family": "yugioh",
    "slug": "archive-abyssrhine-the-atlantean-spirit-17080584",
    "title": "Abyssrhine, the Atlantean Spirit",
    "set": "Card Database · Non-holo stock",
    "number": "17080584"
  },
  {
    "family": "yugioh",
    "slug": "archive-abysstrite-the-atlantean-spirit-9453320",
    "title": "Abysstrite, the Atlantean Spirit",
    "set": "Card Database · Non-holo stock",
    "number": "9453320"
  },
  {
    "family": "yugioh",
    "slug": "archive-accel-synchro-stardust-dragon-30983281",
    "title": "Accel Synchro Stardust Dragon",
    "set": "Card Database · Non-holo stock",
    "number": "30983281"
  },
  {
    "family": "yugioh",
    "slug": "archive-accel-synchron-37675907",
    "title": "Accel Synchron",
    "set": "Card Database · Non-holo stock",
    "number": "37675907"
  },
  {
    "family": "yugioh",
    "slug": "archive-accellight-34838437",
    "title": "Accellight",
    "set": "Card Database · Non-holo stock",
    "number": "34838437"
  },
  {
    "family": "yugioh",
    "slug": "archive-accumulated-fortune-98444741",
    "title": "Accumulated Fortune",
    "set": "Card Database · Non-holo stock",
    "number": "98444741"
  },
  {
    "family": "yugioh",
    "slug": "archive-ace-spades-speculation-10796448",
    "title": "Ace★Spades Speculation",
    "set": "Card Database · Non-holo stock",
    "number": "10796448"
  },
  {
    "family": "yugioh",
    "slug": "archive-achacha-archer-98865920",
    "title": "Achacha Archer",
    "set": "Card Database · Non-holo stock",
    "number": "98865920"
  },
  {
    "family": "yugioh",
    "slug": "archive-achacha-chanbara-62476197",
    "title": "Achacha Chanbara",
    "set": "Card Database · Non-holo stock",
    "number": "62476197"
  },
  {
    "family": "yugioh",
    "slug": "archive-achichi-ignister-15808381",
    "title": "Achichi @Ignister",
    "set": "Card Database · Non-holo stock",
    "number": "15808381"
  },
  {
    "family": "yugioh",
    "slug": "archive-acid-crawler-77568553",
    "title": "Acid Crawler",
    "set": "Card Database · Non-holo stock",
    "number": "77568553"
  },
  {
    "family": "yugioh",
    "slug": "archive-acid-rain-21323861",
    "title": "Acid Rain",
    "set": "Card Database · Non-holo stock",
    "number": "21323861"
  },
  {
    "family": "yugioh",
    "slug": "archive-acid-trap-hole-41356845",
    "title": "Acid Trap Hole",
    "set": "Card Database · Non-holo stock",
    "number": "41356845"
  },
  {
    "family": "yugioh",
    "slug": "archive-acidic-downpour-35956022",
    "title": "Acidic Downpour",
    "set": "Card Database · Non-holo stock",
    "number": "35956022"
  },
  {
    "family": "yugioh",
    "slug": "archive-acorno-21051977",
    "title": "Acorno",
    "set": "Card Database · Non-holo stock",
    "number": "21051977"
  },
  {
    "family": "yugioh",
    "slug": "archive-acrobat-monkey-47372349",
    "title": "Acrobat Monkey",
    "set": "Card Database · Non-holo stock",
    "number": "47372349"
  },
  {
    "family": "yugioh",
    "slug": "archive-acrobatic-magician-33656832",
    "title": "Acrobatic Magician",
    "set": "Card Database · Non-holo stock",
    "number": "33656832"
  },
  {
    "family": "yugioh",
    "slug": "archive-action-magic-double-banking-35498188",
    "title": "Action Magic - Double Banking",
    "set": "Card Database · Non-holo stock",
    "number": "35498188"
  },
  {
    "family": "yugioh",
    "slug": "archive-action-magic-full-turn-99004583",
    "title": "Action Magic - Full Turn",
    "set": "Card Database · Non-holo stock",
    "number": "99004583"
  },
  {
    "family": "yugioh",
    "slug": "archive-ad-libitum-of-despia-81555617",
    "title": "Ad Libitum of Despia",
    "set": "Card Database · Non-holo stock",
    "number": "81555617"
  },
  {
    "family": "yugioh",
    "slug": "archive-adamancipator-analyzer-11302671",
    "title": "Adamancipator Analyzer",
    "set": "Card Database · Non-holo stock",
    "number": "11302671"
  },
  {
    "family": "yugioh",
    "slug": "archive-adamancipator-conductor-24925387",
    "title": "Adamancipator Conductor",
    "set": "Card Database · Non-holo stock",
    "number": "24925387"
  },
  {
    "family": "yugioh",
    "slug": "archive-adamancipator-crystal-dragite-10286023",
    "title": "Adamancipator Crystal - Dragite",
    "set": "Card Database · Non-holo stock",
    "number": "10286023"
  },
  {
    "family": "magic",
    "slug": "nonfoil-yavimaya-cradle-of-growth-261",
    "title": "Yavimaya, Cradle of Growth",
    "set": "Modern Horizons 2 · Nonfoil",
    "number": "261"
  },
  {
    "family": "magic",
    "slug": "nonfoil-esper-sentinel-12",
    "title": "Esper Sentinel",
    "set": "Modern Horizons 2 · Nonfoil",
    "number": "12"
  },
  {
    "family": "magic",
    "slug": "nonfoil-sulfur-falls-269",
    "title": "Sulfur Falls",
    "set": "Marvel Super Heroes Commander · Nonfoil",
    "number": "269"
  },
  {
    "family": "magic",
    "slug": "nonfoil-clifftop-retreat-231",
    "title": "Clifftop Retreat",
    "set": "Marvel Super Heroes Commander · Nonfoil",
    "number": "231"
  },
  {
    "family": "magic",
    "slug": "nonfoil-temple-of-the-false-god-416",
    "title": "Temple of the False God",
    "set": "Secrets of Strixhaven Commander · Nonfoil",
    "number": "416"
  },
  {
    "family": "magic",
    "slug": "nonfoil-temple-garden-301",
    "title": "Temple Garden",
    "set": "Star Trek · Nonfoil",
    "number": "301"
  },
  {
    "family": "magic",
    "slug": "nonfoil-fierce-guardianship-94",
    "title": "Fierce Guardianship",
    "set": "Commander Masters · Nonfoil",
    "number": "94"
  },
  {
    "family": "magic",
    "slug": "nonfoil-dragonskull-summit-238",
    "title": "Dragonskull Summit",
    "set": "Marvel Super Heroes Commander · Nonfoil",
    "number": "238"
  },
  {
    "family": "magic",
    "slug": "nonfoil-chromatic-lantern-73",
    "title": "Chromatic Lantern",
    "set": "Mystery Booster Commander Edition · Nonfoil",
    "number": "73"
  },
  {
    "family": "magic",
    "slug": "nonfoil-sunken-hollow-271",
    "title": "Sunken Hollow",
    "set": "Marvel Super Heroes Commander · Nonfoil",
    "number": "271"
  },
  {
    "family": "magic",
    "slug": "nonfoil-cinder-glade-230",
    "title": "Cinder Glade",
    "set": "Marvel Super Heroes Commander · Nonfoil",
    "number": "230"
  },
  {
    "family": "magic",
    "slug": "nonfoil-otawara-soaring-city-271",
    "title": "Otawara, Soaring City",
    "set": "Kamigawa: Neon Dynasty · Nonfoil",
    "number": "271"
  },
  {
    "family": "magic",
    "slug": "nonfoil-feed-the-swarm-257",
    "title": "Feed the Swarm",
    "set": "Avatar: The Last Airbender Eternal · Nonfoil",
    "number": "257"
  },
  {
    "family": "magic",
    "slug": "nonfoil-garruk-s-uprising-109",
    "title": "Garruk's Uprising",
    "set": "Lorwyn Eclipsed Commander · Nonfoil",
    "number": "109"
  },
  {
    "family": "magic",
    "slug": "nonfoil-smoldering-marsh-266",
    "title": "Smoldering Marsh",
    "set": "Marvel Super Heroes Commander · Nonfoil",
    "number": "266"
  },
  {
    "family": "magic",
    "slug": "nonfoil-the-one-ring-246",
    "title": "The One Ring",
    "set": "The Lord of the Rings: Tales of Middle-earth · Nonfoil",
    "number": "246"
  },
  {
    "family": "magic",
    "slug": "nonfoil-talisman-of-dominance-219",
    "title": "Talisman of Dominance",
    "set": "Marvel Super Heroes Commander · Nonfoil",
    "number": "219"
  },
  {
    "family": "magic",
    "slug": "nonfoil-isolated-chapel-382",
    "title": "Isolated Chapel",
    "set": "Secrets of Strixhaven Commander · Nonfoil",
    "number": "382"
  },
  {
    "family": "magic",
    "slug": "nonfoil-glacial-fortress-248",
    "title": "Glacial Fortress",
    "set": "Marvel Super Heroes Commander · Nonfoil",
    "number": "248"
  },
  {
    "family": "magic",
    "slug": "nonfoil-city-of-brass-62",
    "title": "City of Brass",
    "set": "Teenage Mutant Ninja Turtles Eternal · Nonfoil",
    "number": "62"
  },
  {
    "family": "magic",
    "slug": "nonfoil-faithless-looting-244",
    "title": "Faithless Looting",
    "set": "Secrets of Strixhaven Commander · Nonfoil",
    "number": "244"
  },
  {
    "family": "magic",
    "slug": "nonfoil-hinterland-harbor-250",
    "title": "Hinterland Harbor",
    "set": "Marvel Super Heroes Commander · Nonfoil",
    "number": "250"
  },
  {
    "family": "magic",
    "slug": "nonfoil-mystic-remora-59",
    "title": "Mystic Remora",
    "set": "Dominaria Remastered · Nonfoil",
    "number": "59"
  },
  {
    "family": "magic",
    "slug": "nonfoil-frantic-search-159",
    "title": "Frantic Search",
    "set": "Avatar: The Last Airbender Eternal · Nonfoil",
    "number": "159"
  },
  {
    "family": "magic",
    "slug": "nonfoil-vandalblast-168",
    "title": "Vandalblast",
    "set": "Marvel Super Heroes Commander · Nonfoil",
    "number": "168"
  },
  {
    "family": "magic",
    "slug": "nonfoil-elvish-mystic-205",
    "title": "Elvish Mystic",
    "set": "The Hobbit Eternal · Nonfoil",
    "number": "205"
  },
  {
    "family": "magic",
    "slug": "nonfoil-phyrexian-arena-180",
    "title": "Phyrexian Arena",
    "set": "Foundations · Nonfoil",
    "number": "180"
  },
  {
    "family": "magic",
    "slug": "nonfoil-jeska-s-will-156",
    "title": "Jeska's Will",
    "set": "Murders at Karlov Manor Commander · Nonfoil",
    "number": "156"
  },
  {
    "family": "magic",
    "slug": "nonfoil-prairie-stream-257",
    "title": "Prairie Stream",
    "set": "Marvel Super Heroes Commander · Nonfoil",
    "number": "257"
  },
  {
    "family": "magic",
    "slug": "nonfoil-canopy-vista-227",
    "title": "Canopy Vista",
    "set": "Marvel Super Heroes Commander · Nonfoil",
    "number": "227"
  },
  {
    "family": "magic",
    "slug": "nonfoil-deadly-rollick-147",
    "title": "Deadly Rollick",
    "set": "Commander Masters · Nonfoil",
    "number": "147"
  },
  {
    "family": "magic",
    "slug": "nonfoil-drowned-catacomb-239",
    "title": "Drowned Catacomb",
    "set": "Marvel Super Heroes Commander · Nonfoil",
    "number": "239"
  },
  {
    "family": "magic",
    "slug": "nonfoil-teferi-s-protection-32",
    "title": "Teferi's Protection",
    "set": "Double Masters 2022 · Nonfoil",
    "number": "32"
  },
  {
    "family": "magic",
    "slug": "nonfoil-woodland-cemetery-424",
    "title": "Woodland Cemetery",
    "set": "Secrets of Strixhaven Commander · Nonfoil",
    "number": "424"
  },
  {
    "family": "magic",
    "slug": "nonfoil-cavern-of-souls-269",
    "title": "Cavern of Souls",
    "set": "The Lost Caverns of Ixalan · Nonfoil",
    "number": "269"
  },
  {
    "family": "magic",
    "slug": "nonfoil-sakura-tribe-elder-285",
    "title": "Sakura-Tribe Elder",
    "set": "Secrets of Strixhaven Commander · Nonfoil",
    "number": "285"
  },
  {
    "family": "magic",
    "slug": "nonfoil-vampiric-tutor-108",
    "title": "Vampiric Tutor",
    "set": "Dominaria Remastered · Nonfoil",
    "number": "108"
  },
  {
    "family": "magic",
    "slug": "nonfoil-propaganda-151",
    "title": "Propaganda",
    "set": "Marvel Super Heroes Commander · Nonfoil",
    "number": "151"
  },
  {
    "family": "magic",
    "slug": "nonfoil-eternal-witness-286",
    "title": "Eternal Witness",
    "set": "Commander Masters · Nonfoil",
    "number": "286"
  },
  {
    "family": "magic",
    "slug": "nonfoil-shivan-reef-404",
    "title": "Shivan Reef",
    "set": "Secrets of Strixhaven Commander · Nonfoil",
    "number": "404"
  },
  {
    "family": "magic",
    "slug": "nonfoil-mana-confluence-163",
    "title": "Mana Confluence",
    "set": "Journey into Nyx · Nonfoil",
    "number": "163"
  },
  {
    "family": "magic",
    "slug": "nonfoil-urza-s-saga-259",
    "title": "Urza's Saga",
    "set": "Modern Horizons 2 · Nonfoil",
    "number": "259"
  },
  {
    "family": "magic",
    "slug": "nonfoil-mana-drain-57",
    "title": "Mana Drain",
    "set": "Double Masters 2022 · Nonfoil",
    "number": "57"
  },
  {
    "family": "magic",
    "slug": "nonfoil-lotus-petal-294",
    "title": "Lotus Petal",
    "set": "Tempest · Nonfoil",
    "number": "294"
  },
  {
    "family": "magic",
    "slug": "nonfoil-battlefield-forge-362",
    "title": "Battlefield Forge",
    "set": "Secrets of Strixhaven Commander · Nonfoil",
    "number": "362"
  },
  {
    "family": "magic",
    "slug": "nonfoil-assassin-s-trophy-294",
    "title": "Assassin's Trophy",
    "set": "Secrets of Strixhaven Commander · Nonfoil",
    "number": "294"
  },
  {
    "family": "magic",
    "slug": "nonfoil-enlightened-tutor-6",
    "title": "Enlightened Tutor",
    "set": "Dominaria Remastered · Nonfoil",
    "number": "6"
  },
  {
    "family": "magic",
    "slug": "nonfoil-wayfarer-s-bauble-211",
    "title": "Wayfarer's Bauble",
    "set": "The Hobbit Eternal · Nonfoil",
    "number": "211"
  },
  {
    "family": "magic",
    "slug": "nonfoil-caves-of-koilos-365",
    "title": "Caves of Koilos",
    "set": "Secrets of Strixhaven Commander · Nonfoil",
    "number": "365"
  },
  {
    "family": "magic",
    "slug": "nonfoil-talisman-of-creativity-218",
    "title": "Talisman of Creativity",
    "set": "Marvel Super Heroes Commander · Nonfoil",
    "number": "218"
  },
  {
    "family": "magic",
    "slug": "nonfoil-rootbound-crag-261",
    "title": "Rootbound Crag",
    "set": "Marvel Super Heroes Commander · Nonfoil",
    "number": "261"
  },
  {
    "family": "magic",
    "slug": "nonfoil-victimize-198",
    "title": "Victimize",
    "set": "Tarkir: Dragonstorm Commander · Nonfoil",
    "number": "198"
  },
  {
    "family": "magic",
    "slug": "nonfoil-talisman-of-indulgence-220",
    "title": "Talisman of Indulgence",
    "set": "Marvel Super Heroes Commander · Nonfoil",
    "number": "220"
  },
  {
    "family": "magic",
    "slug": "nonfoil-deadly-dispute-794",
    "title": "Deadly Dispute",
    "set": "Marvel Super Heroes Commander · Nonfoil",
    "number": "794"
  },
  {
    "family": "magic",
    "slug": "nonfoil-black-market-connections-155",
    "title": "Black Market Connections",
    "set": "Marvel Super Heroes Commander · Nonfoil",
    "number": "155"
  },
  {
    "family": "magic",
    "slug": "nonfoil-roaming-throne-258",
    "title": "Roaming Throne",
    "set": "The Lost Caverns of Ixalan · Nonfoil",
    "number": "258"
  },
  {
    "family": "magic",
    "slug": "nonfoil-sunpetal-grove-272",
    "title": "Sunpetal Grove",
    "set": "Marvel Super Heroes Commander · Nonfoil",
    "number": "272"
  },
  {
    "family": "magic",
    "slug": "nonfoil-ashnod-s-altar-368",
    "title": "Ashnod's Altar",
    "set": "Commander Masters · Nonfoil",
    "number": "368"
  },
  {
    "family": "magic",
    "slug": "nonfoil-talisman-of-hierarchy-358",
    "title": "Talisman of Hierarchy",
    "set": "Secrets of Strixhaven Commander · Nonfoil",
    "number": "358"
  },
  {
    "family": "magic",
    "slug": "nonfoil-yavimaya-coast-425",
    "title": "Yavimaya Coast",
    "set": "Secrets of Strixhaven Commander · Nonfoil",
    "number": "425"
  },
  {
    "family": "magic",
    "slug": "nonfoil-llanowar-wastes-383",
    "title": "Llanowar Wastes",
    "set": "Secrets of Strixhaven Commander · Nonfoil",
    "number": "383"
  },
  {
    "family": "magic",
    "slug": "nonfoil-big-score-802",
    "title": "Big Score",
    "set": "Marvel Super Heroes Commander · Nonfoil",
    "number": "802"
  },
  {
    "family": "magic",
    "slug": "nonfoil-talisman-of-progress-221",
    "title": "Talisman of Progress",
    "set": "Marvel Super Heroes Commander · Nonfoil",
    "number": "221"
  },
  {
    "family": "magic",
    "slug": "nonfoil-blood-artist-209",
    "title": "Blood Artist",
    "set": "Secrets of Strixhaven Commander · Nonfoil",
    "number": "209"
  },
  {
    "family": "magic",
    "slug": "nonfoil-war-room-422",
    "title": "War Room",
    "set": "Secrets of Strixhaven Commander · Nonfoil",
    "number": "422"
  },
  {
    "family": "magic",
    "slug": "nonfoil-rejuvenating-springs-260",
    "title": "Rejuvenating Springs",
    "set": "Marvel Super Heroes Commander · Nonfoil",
    "number": "260"
  }
] as const;
