import type { FoilLayer, HolographicProfile } from '../materials/HolographicProfile';
export type Region = 'primary' | 'secondary' | 'stamp';
export type Mechanism = NonNullable<FoilLayer['disabledMechanisms']>[number];
export interface Parameter { group: keyof Pick<FoilLayer, 'diffraction' | 'structure' | 'glints' | 'surface'>; key: string; label: string; min: number; max: number; step: number; fallback?: number; }
const p = (group: Parameter['group'], key: string, label: string, min: number, max: number, step = .01, fallback = 0): Parameter => ({ group, key, label, min, max, step, fallback });
export const mechanisms: Array<{ id: Mechanism; name: string; kind: string; description: string; parameters: Parameter[] }> = [
  { id: 'reflection', name: 'Metallic foil', kind: 'Material response', description: 'Physical metal substrate and the neutral reflection of manufactured cuts.', parameters: [p('surface','metalness','Metallic response',0,1),p('surface','roughness','Foil roughness',.045,1),p('surface','foilReflectance','Silver backing',0,1),p('surface','sheen','Pearl sheen',0,1),p('surface','anisotropy','Directional anisotropy',0,1),p('surface','substrateDarkening','Substrate absorption',0,1)] },
  { id: 'diffraction', name: 'Diffraction', kind: 'Optical pattern', description: 'Grating response in physical micrometres. The selected manufacturing family retains its own angular model.', parameters: [p('diffraction','strength','Spectral strength',0,4),p('diffraction','period','Grating period · µm',.2,4),p('diffraction','bandwidth','Spectral width',.005,.2,.001),p('diffraction','direction','Grating rotation · rad',-3.142,3.142,.001),p('diffraction','crossWidth','Angular width',.01,1),p('diffraction','secondaryOrder','Second spectral order',0,1),p('diffraction','crossing','Crossing grating',0,1),p('diffraction','facetCoupling','Facet coupling',0,1),p('structure','engraving','Etched modulation',0,1),p('structure','scale','Pattern frequency',1,800,1),p('structure','gridStrength','Angular grid',0,1),p('structure','gridScale','Grid frequency',.1,30,.1,6.4),p('structure','gridTravel','Angular travel',1,40,.1,14),p('structure','gridWidth','Grid width',.05,1,.01,.55)] },
  { id: 'sparkle', name: 'Sparkle / microcuts', kind: 'Optical response', description: 'Fixed microfacets selected by real light and view direction. Starlight uses its crossed-cut model here.', parameters: [p('glints','density','Particle density',0,.95),p('glints','scale','Particle frequency',1,1000,1),p('glints','sharpness','Angular sharpness',1,1200,1),p('glints','strength','Flash intensity',0,50,.1),p('glints','spread','Facet spread',.01,1.5)] },
  { id: 'relief', name: 'Etch & emboss', kind: 'Physical relief', description: 'Authored height, surface normals and manufactured facet slopes. These also steer diffraction.', parameters: [p('structure','relief','Emboss depth',0,2),p('structure','patternRelief','Etch depth',0,2),p('structure','facetTilt','Facet inclination',0,2),p('structure','reflectionCoupling','Reflection coupling',0,1,.01,1),p('structure','normalVariance','Normal filtering',0,1),p('surface','patternRoughness','Roughness variation',-.3,.3)] },
  { id: 'varnish', name: 'Raised varnish', kind: 'Physical relief', description: 'Height-derived clearcoat normals, separate from the foil surface below.', parameters: [p('surface','varnishRelief','Varnish height',0,2),p('surface','frameVarnish','Frame varnish',0,1)] },
  { id: 'laminate', name: 'Clear laminate', kind: 'Protective coating', description: 'The outer clearcoat follows the authored laminate coverage.', parameters: [p('surface','laminate','Coat contribution',0,1),p('surface','laminateRoughness','Coat roughness',.045,1)] },
  { id: 'film', name: 'Thin film / pearl', kind: 'Material response', description: 'Physical thin-film interference, independent of grating diffraction.', parameters: [p('surface','iridescence','Interference strength',0,1),p('surface','filmIOR','Film refractive index',1,2.5,.01,1.5),p('surface','filmMin','Minimum thickness · nm',0,2000,5,200),p('surface','filmMax','Maximum thickness · nm',0,2000,5,600),p('surface','pearlBody','Pearl body',0,.5)] },
  { id: 'image', name: 'Image hologram', kind: 'Optical reconstruction', description: 'Ghost-style silver image reconstruction using the card’s registered image/depth data.', parameters: [p('surface','imageHologram','Reconstruction strength',0,1),p('surface','imageDepth','Virtual depth · cm',0,.5,.005,.18),p('surface','imageContrast','Image contrast',.1,4,.01,1.5),p('surface','imageWidth','Angular window',.04,1,.01,.22)] },
];
export const regionLayer = (profile: HolographicProfile, region: Region): FoilLayer | undefined => region === 'primary' ? profile : profile[region];
export function valueOf(layer: FoilLayer, param: Parameter) { return (layer[param.group] as unknown as Record<string, number>)[param.key] ?? param.fallback ?? 0; }
export function setValue(layer: FoilLayer, param: Parameter, value: number) { (layer[param.group] as unknown as Record<string, number>)[param.key] = value; }
export function copyLayer(layer: FoilLayer): FoilLayer {
  return structuredClone({ diffraction: layer.diffraction, structure: layer.structure, glints: layer.glints, surface: layer.surface, ...(layer.enabled === undefined ? {} : { enabled: layer.enabled }), ...(layer.disabledMechanisms ? { disabledMechanisms: layer.disabledMechanisms } : {}) });
}
